"""Add stripe ids to user and app models

Revision ID: 5a316bd07df3
Revises: d69d27a04493
Create Date: 2025-06-23 12:56:51.527421

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5a316bd07df3'
down_revision: Union[str, None] = 'd69d27a04493'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app', sa.Column('stripe_price_id', sa.String(), nullable=True))
    op.add_column('user', sa.Column('stripe_customer_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_user_stripe_customer_id'), 'user', ['stripe_customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_stripe_customer_id'), table_name='user')
    op.drop_column('user', 'stripe_customer_id')
    op.drop_column('app', 'stripe_price_id')
    # ### end Alembic commands ###
